# ArgoCD App: Deploy RBAC roles + bindings
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    # Lab 1.1: RBAC — alice/developer, bob/sre, carol/viewer
spec:
  project: default
  source:
    repoURL: https://github.com/trungctde180766/LABW10.git
    path: rbac
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
